[package]
name = "backend"
version = "0.1.0"
edition = "2021"
address = "0.0.0.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocket = "0.4.6"
